"""
Django settings for MarkFlow project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v*lf)b@bsgib61r9%@=7^mq-&r9cn6*5lwjauo@+3(i_$9#hi+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MarkFlowImpl',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MarkFlow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            r'D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MarkFlow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "markflow",
        "USER":"cyx",
        "PASSWORD":"12345678",
        "HOST":"localhost",
        "PORT":"3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# settings.py
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # 保留API浏览界面
        # 移除HTML渲染器（解决模板依赖问题）
        # 'rest_framework.renderers.TemplateHTMLRenderer',
    ]
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'  # QQ邮箱SMTP服务器
EMAIL_PORT = 587  # QQ邮箱SMTP服务器端口
EMAIL_USE_TLS = True  # 使用TLS加密
EMAIL_HOST_USER = '2022412062@qq.com'  # 您的QQ邮箱地址
EMAIL_HOST_PASSWORD = 'wrvkfswovnhzbbff'  # 您的QQ邮箱SMTP授权码


# settings.py
REDIS_HOST = 'localhost'  # Redis 服务器地址（本地开发用）
REDIS_PORT = 6379         # Redis 默认端口
REDIS_DB = 0              # 使用的数据库编号（0-15）
REDIS_PASSWORD = "123456"# 若 Redis 有密码，添加此行
REDIS_DEFAULT_EXPIRE = 1

# settings.py
# Redis缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",  # Redis服务器地址
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},  # 连接池配置
            "SOCKET_CONNECT_TIMEOUT": 5,  # 连接超时时间(秒)
            "TIMEOUT": 600,  # 核心：默认缓存过期时间，5分钟=300秒
        },
        "KEY_PREFIX": "word_memory"  # 键前缀，避免与其他应用冲突
    }
}

# 会话引擎配置（如果需要）
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'verification.log'),  # 项目根目录/logs/verification.log
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# MarkFlow/settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # 消息代理地址（Redis，与缓存复用）
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # 任务结果存储地址（可选，用于查看任务状态）
CELERY_ACCEPT_CONTENT = ['json']  # 支持的内容格式
CELERY_TASK_SERIALIZER = 'json'  # 任务序列化方式
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化方式
CELERY_TIMEZONE = 'Asia/Shanghai'  # 时区（必须配置，否则定时任务时间可能偏差）

# settings.py
# 缓存同步配置
CACHE_SYNC_INTERVAL = 1  # 同步间隔时间（分钟）
CACHE_SYNC_ENABLED = True  # 是否启用缓存同步