server:
    port: 8082
#    ssl:
#        key-store: classpath:keystore.jks
#        key-store-password: 123321
#        key-store-type: JKS
#        key-alias: myalias

spring:
    datasource:
        url: jdbc:mysql://mysql.sqlpub.com:3306/muwudb
        username: muwumaimaimai
        password: hiiyp4TLx6nMDcM1
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    type-aliases-package: com.hnu.muwu.bean