# Generated by Django 5.2.3 on 2025-07-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词')),
                ('pronunciation', models.CharField(blank=True, max_length=200, null=True, verbose_name='发音')),
                ('definition', models.TextField(verbose_name='释义')),
                ('example_sentence', models.TextField(blank=True, null=True, verbose_name='例句')),
            ],
            options={
                'db_table': 'BaseVocabulary',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密码哈希')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='ImageRecognitionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片路径')),
                ('recognized_words', models.JSONField(blank=True, null=True, verbose_name='识别出的单词')),
                ('selected_words', models.JSONField(blank=True, null=True, verbose_name='用户选择的单词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkFlowImpl.user', verbose_name='用户')),
            ],
            options={
                'db_table': 'ImageRecognitionLogs',
            },
        ),
        migrations.CreateModel(
            name='DailySentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_sentence', models.TextField(verbose_name='生成的句子')),
                ('translation', models.TextField(verbose_name='翻译')),
                ('used_words', models.JSONField(blank=True, null=True, verbose_name='使用的单词')),
                ('date', models.DateField(verbose_name='生成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkFlowImpl.user', verbose_name='用户')),
            ],
            options={
                'db_table': 'DailySentences',
            },
        ),
        migrations.CreateModel(
            name='UserWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_word', models.CharField(blank=True, max_length=100, null=True, verbose_name='自定义单词')),
                ('custom_definition', models.TextField(blank=True, null=True, verbose_name='自定义释义')),
                ('custom_pronunciation', models.CharField(blank=True, max_length=200, null=True, verbose_name='自定义发音')),
                ('familiarity_level', models.IntegerField(default=0, verbose_name='熟悉度等级(0-10)')),
                ('priority_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='优先级分数')),
                ('learning_count', models.IntegerField(default=0, verbose_name='学习次数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确次数')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('source', models.CharField(choices=[('base_vocab', '基础词汇'), ('custom', '自定义'), ('image_recognition', '图片识别')], max_length=50, verbose_name='来源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkFlowImpl.user', verbose_name='用户')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkFlowImpl.basevocabulary', verbose_name='基础词汇')),
            ],
            options={
                'db_table': 'UserWords',
            },
        ),
    ]
