# Generated by Django 5.2.3 on 2025-07-03 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkFlowImpl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userwords',
            name='custom_definition',
        ),
        migrations.RemoveField(
            model_name='userwords',
            name='custom_pronunciation',
        ),
        migrations.RemoveField(
            model_name='userwords',
            name='custom_word',
        ),
        migrations.RemoveField(
            model_name='userwords',
            name='word',
        ),
        migrations.AddField(
            model_name='userwords',
            name='word_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MarkFlowImpl.basevocabulary', verbose_name='关联基础词汇Id'),
        ),
    ]
