# Generated by Django 5.2.3 on 2025-07-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkFlowImpl', '0002_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwords',
            old_name='word_id',
            new_name='word',
        ),
    ]
