# Generated by Django 5.2.3 on 2025-07-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkFlowImpl', '0003_rename_word_id_userwords_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevocabulary',
            name='synonyms',
            field=models.TextField(blank=True, null=True, verbose_name='近义词'),
        ),
    ]
