# Generated by Django 5.2.3 on 2025-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkFlowImpl', '0004_basevocabulary_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='basevocabulary',
            name='confusing_words',
            field=models.TextField(blank=True, null=True, verbose_name='易混淆词'),
        ),
    ]
