# Generated by Django 5.2.3 on 2025-09-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkFlowImpl', '0005_basevocabulary_confusing_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwords',
            name='source',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名'),
        ),
    ]
